# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c1825b48a068d2dcda40135acf77d984"
name = "first-test-app"
handle = "first-test-app-170"
application_url = "https://dale-cage-combat-vista.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://dale-cage-combat-vista.trycloudflare.com/auth/callback", "https://dale-cage-combat-vista.trycloudflare.com/auth/shopify/callback", "https://dale-cage-combat-vista.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
